apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-intro-devops-casino
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-intro-devops-casino
  template:
    metadata:
      labels:
        app: backend-intro-devops-casino
    spec:
      # Regla para forzar el reparto de pods entre nodos (requisito del lab 3.3)
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: backend-intro-devops-casino
      containers:
      - name: backend-intro-devops-casino
        # Los marcadores <ACCOUNT_ID> y <REGION> serán reemplazados automáticamente por GitHub Actions
        image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/backend-intro-devops-casino:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgres-service" # Nombre interno de tu Base de Datos en K8s
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: casino-secrets # Llama a la caja fuerte que creamos en el paso 4.1
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: casino-secrets
              key: DB_PASSWORD
        resources:
          requests:
            cpu: "50m" # Obligatorio para que el HPA pueda calcular el % de uso
          limits:
            cpu: "250m"
        
        livenessProbe:
          httpGet:
            path: /       # Cambiado a la ruta raíz que responde 200 OK
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health # Cambiado a la ruta que verifica la BD en Node
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10