apiVersion: v1
kind: Service
metadata:
  name: backend-intro-devops-casino
spec:
  type: ClusterIP  # ClusterIP significa que es 100% privado, no sale a internet
  selector:
    app: backend-intro-devops-casino
  ports:
  - port: 3000
    targetPort: 3000