name: CI/CD Pipeline Casino Backend

on:
  push:
    branches:
      - deploy

env:
  ECR_REPOSITORY: casino-backend

jobs:
  build-and-push:
    name: Construir y subir imagen a Amazon ECR
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 3. Iniciar sesión en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 4. Construir, etiquetar y publicar la imagen
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:v1.0.0 .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY

  deploy:
    name: Desplegar en EC2 Backend
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar vía SSH usando Bastion Host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_BACKEND_PRIVATE_IP }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          proxy_host: ${{ secrets.AWS_HOST_IP_FRONTEND }}
          proxy_username: ec2-user
          proxy_key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 590183930707.dkr.ecr.us-east-1.amazonaws.com
            docker pull 590183930707.dkr.ecr.us-east-1.amazonaws.com/casino-backend:latest
            docker rm -f casino_backend || true
            docker run -d \
              --name casino_backend \
              -p 3000:3000 \
              -e DB_HOST=${{ secrets.AWS_DB_PRIVATE_IP }} \
              -e DB_USER=casino_user \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_NAME=casino_db \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e CORS_ORIGIN="*" \
              --restart unless-stopped \
              590183930707.dkr.ecr.us-east-1.amazonaws.com/casino-backend:latest